# Generated by Django 4.2.5 on 2023-09-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcds', '0002_record_clinical_results_record_genatic_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
