# Generated by Django 4.2.5 on 2023-11-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcds', '0005_record_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
