# Generated by Django 4.2.5 on 2023-11-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcds', '0006_alter_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='info',
            field=models.TextField(default=1, max_length=105),
            preserve_default=False,
        ),
    ]
